### ISSUE TITLE
Pre-trained weights?

### ISSUE THREAD

**Issue by htalibart** [mmodbasel/HighContentScreening#1]
Hi,

Thank you for making your code public!

Would it be possible for you to provide pre-trained models?

Thanks!

**Comment by mmodbasel** [comment]
We just added a model checkpoint containing pre-trained weights. You can find them in [pretrained/](https://github.com/mmodbasel/HighContentScreening/tree/master/pretrained).

**Comment by htalibart** [comment]
Awesome, thank you very much!

**Comment by htalibart** [comment]
Hi again, could you also provide the associated vocabulary file...? Thanks!

**Comment by ManuelSe** [comment]
The vocabulary used to train the model is also contained in the provided checkpoint file. You can access it like this:
```python
import torch
checkpoint = torch.load("../pretrained/2D_similarity_model_full.ckpt", map_location="cpu")
vocabulary = checkpoint["hyper_parameters"]["args"].vocabulary
```
In fact, the checkpoint contains all hyperparameters used to train the model.
